### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by im-kulikov** [dmtrs/EWebTerm#1]
Интересно, жив ли проект, не так давно внёс правки в https://github.com/yiiext/webshell-module , могу поделиться наработками

**Comment by dmtrs** [comment]
Hello there, 

I am not speaking Russian and google translate is not helping.

I am not developing this simple extension any more. Not sure what the reference to yiiext/webshell-module is about.

**Comment by im-kulikov** [comment]
Oh, I'm sorry.

I'm fix small issues for wterm when using with new version of jquery. If this help, I can make pull request 

Sorry for bad English, it's not native language.
